"use client"

import {useState} from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./(my-components)/sidebar/page";
import Prompts from "./(my-components)/prompt/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [promptVisibility,setPromptVisibility]  = useState<boolean>(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="grid grid-cols-12 grid-rows-4 w-full h-full">
          <SideBar setPromptVisibility={setPromptVisibility}/>
          <div className="grid col-span-10 row-span-2 pt-15">
            {children}
          </div>
          <Prompts promptVisibility={promptVisibility} />
        </div>
      </body>
    </html>
  );
}
